stages:
 - build
 - deploy

build backend:
 stage: build
 only:
  refs:
   - main
 tags:
  - main
 script:
  - ./mvnw clean package
  - docker build -t web-project .

deploy backend:
 stage: deploy
 only:
  refs:
   - main
 tags:
  - main
 script:
  - cd /home/ubuntu/web-project
  - docker-compose down
  - docker-compose up -d
