
POST http://localhost:9000/api/public/users
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Test",
  "email": "test@gmail.com",
  "birthdate": "1970-01-01",
  "password": "test",
  "gender": "Male"
}

###
POST http://localhost:9000/api/public/login
Content-Type: application/json


{
  "email": "test@gmail.com",
  "password": "test"
}

###
GET http://localhost:9000/api/public/products3?page=3&orderBy=id&userId=56
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdWJqZWN0IiwiaWQiOjU3LCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjY5ODE1NDM0LCJleHAiOjE2Njk4MTkwMzR9.RVsh7Ei8iDJjGjTA_g1fmM8HCqgL8nGosR1dF4S92GQ